spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dinnercheng/config-server.git
          search-paths: /config-repo
          username: chadsea@sina.com
          password: chadsea1009


server:
  port: 7001



